0.178

diff --git a/scripts/choose_rom b/scripts/choose_rom
--- a/scripts/choose_rom
+++ b/scripts/choose_rom
@@ -37,65 +37,13 @@ then
   
 else
 
-  cd original_update
-
-  #
-  # Check for any ZIP files in original_update
-  #
-  zip_cmd=`find . ! -name . -prune -type f | grep -i -m 1 \\.zip$`
- 
-  #
-  # Check for any TAR files in original_update
-  #
-  tar_cmd=`find . ! -name . -prune -type f | grep -i -m 1 \\.tar$`
-
-  #
-  # Check for *.APP or *.app in original_update
-  #
-  app_cmd=`find . ! -name . -prune -type f | grep -i -m 1 \\.app$`
-
-  #
-  # Check for WORKING_* folder in original_update
-  #
-  wkg_cmd=`find . ! -name . -prune -type d | grep "WORKING_"`
-
-  cd ..
-
-  if [ "$zip_cmd" == "" ] && [ "$tar_cmd" == "" ] && [ "$app_cmd" == "" ] && [ "$wkg_cmd" == "" ]
-  then
-
-    #
-    # Check for factoryfs.img (cache.img and zImage are optional)
-    #  
-    if [! -e original_update/factoryfs.img]
-    then
-
-      #
-      # Check for system.img and boot.img in original_update  
-      #
-
-      # We'll prompt for a Null boot.img if no boot.img found
-      if [ ! -e original_update/system.img ]
-      then
-
-        # No system.img found, check for boot.img
-
-        if [ -e original_update/boot.img ]
-        then
-        echo "错误: 没有发现original_update/system.img"
-        else
-          echo
-        echo "错误: 在original_update文件夹没有发现ROM!"
-        fi
-
-        exit 0
-      fi
-    fi
-
-  fi
-
-
   grep_cmd=`scripts/grep_roms`
+
+  if [ "$grep_cmd" == "" ]
+  then
+    echo "Error: No ROMs found under original_update folder!"
+    exit 0
+  fi
 
   count=0
   rm -f temp.list
@@ -116,9 +64,22 @@ else
     if [ "$filename" == "system.img" ]
     then
       filename="system.img and boot.img"
+
+    elif [ "$filename" == "factoryfs.rfs" ]
+    then
+      filename="factoryfs.rfs, cache.rfs and zImage"
+
     elif [ "$filename" == "factoryfs.img" ]
     then
       filename="factoryfs.img, cache.img and zImage"
+
+    elif [ "$filename" == "PDA.tar.md5" ]
+    then
+      filename="PDA.tar.md5, CSC.tar.md5 and PHONE.tar.md5"
+
+    elif [ "$filename" == "PDA.tar" ]
+    then
+      filename="PDA.tar, CSC.tar and PHONE.tar"
     fi
 
     echo "  ($count) $filename" >> temp.list
@@ -158,34 +119,55 @@ else
 fi
 
 
-if [ "$file_chosen" == "system.img" ]
+if [ ! -d "original_update/$file_chosen" ]
 then
-  scripts/img_files_to_working_folder create_working $1
-  exit $?
 
-elif [ "$file_chosen" == "factoryfs.img" ]
-then
-  scripts/simg_files_to_working_folder create_working $1
-  exit $?
+  if [ "$file_chosen" == "system.img" ]
+  then
+    scripts/img_files_to_working_folder create_working $1
+    exit $?
 
-elif [ "`echo $file_chosen | grep -i \\.zip$`" != "" ] && [ ! -d "original_update/$file_chosen" ]
-then
-  scripts/zip_file_to_working_folder "$file_chosen" $1
-  exit $?
+  elif [ "$file_chosen" == "factoryfs.rfs" ]
+  then
+    scripts/rfs_files_to_working_folder create_working $1
+    exit $?
 
-elif [ "`echo $file_chosen | grep -i \\.tar$`" != "" ] && [ ! -d "original_update/$file_chosen" ]
-then
-  scripts/tar_file_to_working_folder "$file_chosen" $1
-  exit $?
+  elif [ "$file_chosen" == "PDA.tar" ]
+  then
+    scripts/sgs_tar_files_to_working_folder create_working $1
+    exit $?
 
-elif [ "`echo $file_chosen | grep -i \\.app$`" != "" ] && [ ! -d "original_update/$file_chosen" ]
-then
-  scripts/app_file_to_working_folder "$file_chosen" $1
-  exit $?
+  elif [ "$file_chosen" == "PDA.tar.md5" ]
+  then
+    scripts/sgs_tarmd5_files_to_working_folder create_working $1
+    exit $?
 
-elif [ "`echo $file_chosen | grep -m 1 \"^WORKING_\"`" != "" ]
-then
-  scripts/wkg_to_working_folder "$file_chosen" $1
-  exit $?
-fi 
+  elif [ "$file_chosen" == "factoryfs.img" ]
+  then
+    scripts/simg_files_to_working_folder create_working $1
+    exit $?
+
+  elif [ "`echo $file_chosen | grep -i \\.zip$`" != "" ]
+  then
+    scripts/zip_file_to_working_folder "$file_chosen" $1
+    exit $?
+
+  elif [ "`echo $file_chosen | grep -i \\.tar$`" != "" ]
+  then
+    scripts/tar_file_to_working_folder "$file_chosen" $1
+    exit $?
+
+  elif [ "`echo $file_chosen | grep -i \\.app$`" != "" ]
+  then
+    scripts/app_file_to_working_folder "$file_chosen" $1
+    exit $?
+  fi
+
+else
+  if [ "`echo $file_chosen | grep -m 1 \"^WORKING_\"`" != "" ]
+  then
+    scripts/wkg_to_working_folder "$file_chosen" $1
+    exit $?
+  fi 
+fi
 
